- alias: "Let's Encrypt Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt

- alias: "Exterior lights on with motion after dark"
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    - service: switch.turn_on
      entity_id: switch.outside_front_lights

- alias: "Exterior lights off after 5 minutes no motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'off'
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.outside_front_lights

# - alias: "Exterior lighting on after dark"
#   trigger:
#     - platform: sun
#       event: sunset
#       offset: '00:30:00'
#   action:
#     - service: switch.turn_on
#       entity_id: switch.outside_front_lights
#
# - alias: "Exterior lighting off at midnight"
#   trigger:
#     platform: time
#     at: '00:00:00'
#   action:
#     service: switch.turn_off
#     entity_id: switch.outside_front_lights
