homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml

# Enable
introduction:
frontend:
config:
conversation:
discovery:
history:
logbook:
map:
updater:

# Include
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

#Configurations
zwave:
  usb_path: /dev/ttyAMA0

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
