- platform: command_line
    switches:
      # Toggles Living Room Roku TV
      office_tv_power:
        command_on: 'curl -X POST http://10.0.0.5:8060/keypress/PowerOn'
        command_off: 'curl -X POST http://10.0.0.5:8060/keypress/PowerOff'
        command_state: 'curl -s GET http://10.0.0.5:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
        value_template: '{{ value == "ON" }}'
